import Link from 'next/link';
import type { Metadata } from 'next';
import { buildMetadata } from '@/lib/seo';
import { PHONE_DISPLAY, site } from '@/lib/site';
import { Breadcrumbs } from '@/components/Breadcrumbs';
import { MobileCallBar } from '@/components/MobileCallBar';

export const metadata: Metadata = buildMetadata({
  title: 'Privacy Policy | Sofa Cleaning London',
  description:
    'What we do with your information when you contact Sofa Cleaning London, and what this website does and does not collect.',
  path: '/privacy-policy/',
});

/**
 * NOTE FOR THE SITE OWNER
 *
 * This describes how the site is actually built: it is a static site with no
 * forms posting anywhere, no analytics and no cookies, and the quote forms hand
 * off to WhatsApp rather than submitting. Every statement below is true of the
 * code as shipped.
 *
 * If you later add analytics, a pixel, a chat widget or a server-side form,
 * this page stops being accurate and must be updated — and you will also need a
 * cookie consent mechanism under PECR. Have a solicitor review it before you
 * rely on it for a business of any size.
 */
export default function PrivacyPage() {
  const updated = '21 September 2026';

  return (
    <>
      <Breadcrumbs crumbs={[{ name: 'Home', path: '/' }, { name: 'Privacy policy' }]} />

      <section className="bg-gradient-to-b from-brand-50 to-white">
        <div className="container-content py-10 sm:py-14">
          <div className="max-w-3xl">
            <p className="eyebrow">Legal</p>
            <h1 className="mt-2.5 text-[2rem] font-extrabold leading-[1.12] tracking-tight sm:text-4xl">
              Privacy policy
            </h1>
            <p className="mt-4 text-sm text-ink-muted">Last updated: {updated}</p>
          </div>
        </div>
      </section>

      <section>
        <div className="container-content py-10 sm:py-14">
          <div className="prose-body max-w-prose">
            <h2 className="text-xl font-extrabold text-ink">What this website collects</h2>
            <p>
              Nothing. This site is a set of static pages. It does not set cookies, it does not run
              analytics, it does not load a tracking pixel, and it has no server that receives form
              submissions.
            </p>
            <p>
              The quote forms on this site do not submit anywhere. When you press the button, your
              browser opens WhatsApp with the message written out and you press send yourself. Until
              you do that, the details you typed exist only in your own browser and are lost when you
              close the tab.
            </p>

            <h2 className="mt-9 text-xl font-extrabold text-ink">What happens when you contact us</h2>
            <p>
              When you call, message us on WhatsApp or send an email, we receive whatever you choose
              to tell us — typically your name, phone number, address or postcode, and a description
              of the work. We use it to give you a price, arrange a visit, carry out the work and
              invoice you. That is all.
            </p>
            <p>
              We keep enquiry and job records for as long as we need them to run the business and to
              meet our record-keeping obligations, which for invoices under UK tax rules is six
              years. Enquiries that do not become jobs are deleted once they are plainly no longer
              live.
            </p>
            <p>
              We do not sell your details, we do not share them for marketing, and we do not add you
              to a mailing list because you asked for a quote.
            </p>

            <h2 className="mt-9 text-xl font-extrabold text-ink">WhatsApp</h2>
            <p>
              WhatsApp is operated by Meta Platforms, not by us. If you contact us through it, your
              use of WhatsApp is governed by Meta&rsquo;s own privacy policy as well as this one.
              Message content is end-to-end encrypted between your device and ours, but Meta holds
              metadata about the conversation. If you would rather not use it, call or email instead.
            </p>

            <h2 className="mt-9 text-xl font-extrabold text-ink">Hosting</h2>
            <p>
              Our hosting provider will keep standard server logs — IP address, browser type, the
              page requested and the time — for security and diagnostics. These are generated by the
              hosting infrastructure rather than by anything on this site, and we do not use them to
              build a profile of you.
            </p>

            <h2 className="mt-9 text-xl font-extrabold text-ink">Your rights</h2>
            <p>
              Under UK GDPR you can ask us what personal data we hold about you, ask us to correct
              it, ask us to delete it where we have no continuing legal reason to keep it, object to
              a particular use of it, or ask for a copy. Contact us on {PHONE_DISPLAY} or at{' '}
              <a href={`mailto:${site.email}`}>{site.email}</a> and we will respond within one month.
            </p>
            <p>
              If you are not satisfied with how we have handled your data you can complain to the
              Information Commissioner&rsquo;s Office at{' '}
              <a href="https://ico.org.uk" rel="noopener nofollow">
                ico.org.uk
              </a>
              , or on 0303 123 1113.
            </p>

            <h2 className="mt-9 text-xl font-extrabold text-ink">Changes to this policy</h2>
            <p>
              If we add analytics, a booking system or anything else that changes what is collected,
              we will update this page and change the date at the top. The version you are reading
              describes the site exactly as it is built today.
            </p>

            <p className="mt-9">
              See also our{' '}
              <Link href="/terms/">terms of service</Link>, or{' '}
              <Link href="/contact-us/">contact us</Link> with any question about this policy.
            </p>
          </div>
        </div>
      </section>

      <MobileCallBar />
    </>
  );
}
